version: '3'

services:

    web:
        build: .
        container_name: web
        ports:
        - 5000:5000
        restart: always
        command: python application.py run -h 0.0.0.0
        environment:
        - CELERY_BROKER_URL=redis://redis:6379/0
        - CELERY_RESULT_BACKEND=redis://redis:6379/0
        - PYTHONUNBUFFERED=1
        depends_on:
        - redis
        labels:
            kompose.service.type: LoadBalancer

    worker:
        build: .
        command: celery --app=models.tasks.celery worker --task-events  --loglevel=info --without-gossip --without-mingle -Ofair
        restart: always
        environment:
        - CELERY_BROKER_URL=redis://redis:6379/0
        - CELERY_RESULT_BACKEND=redis://redis:6379/0
        depends_on:
        - web
        - redis

    redis:
        image: redis:6-alpine

    dashboard:
        build: .
        command:  flower --app=models.tasks.celery flower --port=5555 --broker=redis://redis:6379/0
        ports:
            - 5556:5555
        restart: always
        environment:
            - CELERY_BROKER_URL=redis://redis:6379/0
            - CELERY_RESULT_BACKEND=redis://redis:6379/0
        depends_on:
            - web
            - redis
            - worker
        labels:
            kompose.service.type: LoadBalancer